version: '3.9'

services:
  school-dev:
    container_name: school-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - memcached
      - elasticsearch
    links:
      - postgres
      - memcached
    env_file:
      - .env.local
    command: npm run start:debug
    ports:
      - 3000:3000
    networks:
      - school-media

  postgres:
    container_name: school-dev-db
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env.local
      #- ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5432:5432'
    networks:
      - school-media

  adminer:
    container_name: school-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - school-media

  memcached:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - '11211:11211'
    restart: always
    networks:
      - school-media

  #
  #  Elasticsearch
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: 'elasticsearch'
    hostname: 'elasticsearch'
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch
      - school-media

  #
  #  Kibana (Elasticsearch Dashboard)
  #
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: 'kibana'
    hostname: 'kibana'
    restart: always
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch
      - school-media

volumes:
  elasticsearch:

networks:
  school-media:
    driver: bridge
  elasticsearch:
