export const DATABASE_TABLE = {
  USERS: {
    NAME: 'users',
    SCHEMA: {
      ID: 'id',
      USERNAME: 'username',
      PASSWORD: 'password',
      DISPLAY_NAME: 'display_name',
      PHONE: 'phone',
      EMAIL: 'email',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  ROLE: {
    NAME: 'role',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
    },
  },
  USER_ROLE: {
    NAME: 'user_role',
    SCHEMA: {
      ID: 'id',
      USER_ID: 'user_id',
      ROLE_ID: 'role_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  STUDENT: {
    NAME: 'student',
    SCHEMA: {
      ID: 'id',
      USER_ID: 'user_id',
      PARENT_ID: 'parent_id',
    },
  },
  TEACHER: {
    NAME: 'teacher',
    SCHEMA: {
      ID: 'id',
      USER_ID: 'user_id',
    },
  },
  PARENT: {
    NAME: 'parent',
    SCHEMA: {
      ID: 'id',
      USER_ID: 'user_id',
    },
  },
  STUDENT_PARENT: {
    NAME: 'student_parent',
    SCHEMA: {
      ID: 'id',
      STUDENT_ID: 'student_id',
      PARENT_ID: 'parent_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  SUBJECT: {
    NAME: 'subject',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  GROUP: {
    NAME: 'group',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  SUBJECT_GROUP: {
    NAME: 'subject_group',
    SCHEMA: {
      ID: 'id',
      SUBJECT_ID: 'subject_id',
      GROUP_ID: 'group_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  GRADE: {
    NAME: 'grade',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      GRADE_ID: 'grade_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  CLASSROOM: {
    NAME: 'classroom',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      GRADE_ID: 'grade_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  SEMESTER: {
    NAME: 'semester',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      START_DATE: 'start_date',
      END_DATE: 'end_date',
      YEAR_ID: 'year_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  YEAR: {
    NAME: 'year',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      START_DATE: 'start_date',
      END_DATE: 'end_date',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  CLASSROOM_YEAR: {
    NAME: 'classroom_year',
    SCHEMA: {
      ID: 'id',
      CLASSROOM_ID: 'classroom_id',
      YEAR_ID: 'year_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  YEAR_GRADE: {
    NAME: 'year_grade',
    SCHEMA: {
      ID: 'id',
      YEAR_ID: 'year_id',
      GRADE_ID: 'grade_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  TEACHER_SUBJECT: {
    NAME: 'teacher_subject',
    SCHEMA: {
      ID: 'id',
      TEACHER_ID: 'teacher_id',
      SUBJECT_ID: 'subject_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  CLASSROOM_YEAR_STUDENT: {
    NAME: 'classroom_year_student',
    SCHEMA: {
      ID: 'id',
      CLASSROOM_YEAR_ID: 'classroom_year_id',
      STUDENT_ID: 'student_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
  CLASSROOM_YEAR_ASSIGNMENT: {
    NAME: 'classroom_year_assignment',
    SCHEMA: {
      ID: 'id',
      CLASSROOM_YEAR_ID: 'classroom_year_id',
      TEACHER_SUBJECT_ID: 'teacher_subject_id',
      CREATED_AT: 'created_at',
      CREATED_BY: 'created_by',
      UPDATED_AT: 'updated_at',
      UPDATED_BY: 'updated_by',
      DELETED_AT: 'deleted_at',
      DELETED_BY: 'deleted_by',
    },
  },
};
