export const UNPROCESSABLE_ENTITY_EXCEPTION = {
  CATEGORY: {
    NAME: {
      FORMAT_IS_NOT_VALID: 'CATEGORY.NAME.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'CATEGORY.NAME.IS_NOT_EMPTY',
    },
    DESCRIPTION: {
      FORMAT_IS_NOT_VALID: 'CATEGORY.DESCRIPTION.FORMAT_IS_NOT_VALID',
    },
  },
};
