export const UNPROCESSABLE_ENTITY_EXCEPTION = {
  CATEGORY: {
    NAME: {
      FORMAT_IS_NOT_VALID: 'CATEGORY.NAME.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'CATEGORY.NAME.IS_NOT_EMPTY',
    },
    DESCRIPTION: {
      FORMAT_IS_NOT_VALID: 'CATEGORY.DESCRIPTION.FORMAT_IS_NOT_VALID',
    },
  },
  COURSE: {
    NAME: {
      FORMAT_IS_NOT_VALID: 'COURSE.NAME.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'COURSE.NAME.IS_NOT_EMPTY',
    },
    DESCRIPTION: {
      FORMAT_IS_NOT_VALID: 'COURSE.DESCRIPTION.FORMAT_IS_NOT_VALID',
    },
    IMAGE_URL: {
      FORMAT_IS_NOT_VALID: 'COURSE.IMAGE_URL.FORMAT_IS_NOT_VALID',
    },
    CATEGORY_ID: {
      FORMAT_IS_NOT_VALID: 'COURSE.CATEGORY_ID.FORMAT_IS_NOT_VALID',
    },
    STUDENT_ID: {
      FORMAT_IS_NOT_VALID: 'COURSE.STUDENT_ID.FORMAT_IS_NOT_VALID',
    },
  },
  SECTION: {
    NAME: {
      FORMAT_IS_NOT_VALID: 'SECTION.NAME.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'SECTION.NAME.IS_NOT_EMPTY',
    },
    COURSE_ID: {
      FORMAT_IS_NOT_VALID: 'SECTION.COURSE_ID.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'SECTION.COURSE_ID.IS_NOT_EMPTY',
    },
  },
  LESSON: {
    TITLE: {
      FORMAT_IS_NOT_VALID: 'LESSON.TITLE.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'LESSON.TITLE.IS_NOT_EMPTY',
    },
    BODY: {
      FORMAT_IS_NOT_VALID: 'LESSON.BODY.FORMAT_IS_NOT_VALID',
    },
    SECTION_ID: {
      FORMAT_IS_NOT_VALID: 'LESSON.SECTION_ID.FORMAT_IS_NOT_VALID',
      IS_NOT_EMPTY: 'LESSON.SECTION_ID.IS_NOT_EMPTY',
    },
    VIDEO_URL: {
      FORMAT_IS_NOT_VALID: 'LESSON.VIDEO_URL.FORMAT_IS_NOT_VALID',
    },
  },
};
